#! /bin/sh
#PBS -N pmode_j12_1
#PBS -o pmode_j12_1.out
#PBS -e pmode_j12_1.err
#PBS -M gordon.stephenson@usm.edu
#PBS -m bea
#PBS -A ONRDC38645449
#PBS -S /bin/bash
#PBS -l walltime=4:00:00
#PBS -q standard
#PBS -l select=1:ncpus=1
# Change to the specified directory
cd /p/work1/grstephe/hycom/GLBc0.04/expt_22.1
# Execute the serial executable on 1 core
aprun -n 1 ./pmodes_apr.x  < ./pmode_221_12_1.in > ./pmode_221_12_1_may.out
