#! /bin/sh
#PBS -N Nj31_1
#PBS -o Nj31_1.out
#PBS -e Nj31_1.err
#PBS -M gordon.stephenson@usm.edu
#PBS -m bea
#PBS -A ONRDC38645449
#PBS -S /bin/bash
#PBS -l walltime=00:30:00
#PBS -q standard
#PBS -l select=1:ncpus=1
# Change to the specified directory
cd /p/work1/grstephe/hycom/GLBc0.04/expt_22.1
# Execute the serial executable on 1 core
aprun -n 1 ./mean_N_c004_v1.x  < ./mean_N_221_31_1.in > ./mean_N_221_31_1.out
