#! /bin/sh
#PBS -N Sj21_1
#PBS -o Sj21_1.out
#PBS -e Sj21_1.err
#PBS -M gordon.stephenson@usm.edu
#PBS -m bea
#PBS -A ONRDC38645449
#PBS -S /bin/bash
#PBS -l walltime=30:00:00
#PBS -q standard
#PBS -l select=1:ncpus=1
# Change to the specified directory
cd /p/work1/grstephe/hycom/GLBc0.04/expt_22.1
# Execute the serial executable on 1 core
aprun -n 1 ./mean_S_c004_v1.x  < ./mean_S_221_21_1.in > ./mean_S_221_21_1.out
