#! /bin/sh
#PBS -N Tj1_1
#PBS -o Tj1_1.out
#PBS -e Tj1_1.err
#PBS -M gordon.stephenson@usm.edu
#PBS -m bea
#PBS -A ONRDC38645449
#PBS -S /bin/bash
#PBS -l walltime=30:00:00
#PBS -q standard
#PBS -l select=1:ncpus=1
# Change to the specified directory
cd /p/work1/grstephe/hycom/GLBc0.04/expt_22.1
# Execute the serial executable on 1 core
aprun -n 1 ./mean_T_c004_v1.x  < ./mean_T_221_1_1.in > ./mean_T_221_1_1.out
